# Generated by Django 5.0.6 on 2024-07-02 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_label', models.CharField(max_length=50)),
                ('task_status', models.CharField(choices=[('TD', 'to do'), ('DOING', 'doing'), ('DONE', 'completed')], default='to do', max_length=10)),
                ('task_description', models.CharField(max_length=255)),
                ('task_image', models.ImageField(default=None, upload_to='task_images')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
