# Generated by Django 5.0.6 on 2024-07-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('TD', 'to do'), ('DG', 'doing'), ('DN', 'done')], default='TD', max_length=2),
        ),
    ]
