# Generated by Django 5.0.6 on 2024-07-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
